# Generated by Django 3.1.5 on 2021-01-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
