# Generated by Django 3.1.6 on 2021-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210215_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
