# Generated by Django 3.1.6 on 2021-02-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210216_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='#C7C7C7', max_length=10),
            preserve_default=False,
        ),
    ]
